title: Del Malandrin
author: Andrew Malandrin
email: del_malandrin@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Página criada como exercício para a tarefa 4 do curso de pages do github.

# social links
twitter_username: delmalandrin
github_username:  andrewmalandrin
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
